### ISSUE TITLE
Relaunch as a Hugo powered site.

### ISSUE THREAD

**Issue by jamesrwilliams** [jamesrwilliams/personal-site#1]
Following things are still outstanding:

- [X] Write up on process and rationale.
- [x] Full marks on Lighthouse
- [X] ~404 Page Design~ See #8 instead.
- [X] ~Service Worker~ - See #9 instead.
- [x] ~Migrate all WordPress posts~
- [x] ~Implement correct JSON-LD~
- [x] ~OpenGraph tags for social~
- [x] ~Google Analytics (or an alternative).~
- [X] ~Print Stylesheet for posts.~ See #6 instead.

**Comment by jamesrwilliams** [comment]
We’re live!
